language: cpp

compiler: clang

sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get upgrade cmake
- sudo apt-get install -qq qt5-default

before_script:
- mkdir build
- cd build
- cmake ../RBTree

script: make